# Generated by Django 2.0 on 2018-08-25 08:41

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sentiment_array', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=10), size=None)),
                ('average_sentiment', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resting', models.DecimalField(decimal_places=2, max_digits=10)),
                ('out_of_range', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fat_burn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cardio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('message', models.CharField(max_length=300)),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathos_backend.DailyReport')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SleepRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('light', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deep', models.DecimalField(decimal_places=2, max_digits=10)),
                ('awake', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathos_backend.Patient'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='daily_heart_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathos_backend.HeartRate'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='daily_sleep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathos_backend.SleepRate'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathos_backend.Patient'),
        ),
    ]
