# Generated by Django 2.0 on 2018-08-25 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathos_backend', '0002_auto_20180825_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pathos_backend.Doctor'),
            preserve_default=False,
        ),
    ]
